trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "Running on branch: ${{ variables['Build.SourceBranchName'] }}"
    displayName: "Branch: ${{ variables['Build.SourceBranchName'] }}"
  - template: template.yml
    parameters:
      scenario: all branches
  - template: template.yml
    parameters:
      scenario: main branch only
      executeScenario: ${{ eq(variables['Build.SourceBranchName'], 'main') }}
