trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: template.yml
    parameters:
      scenario: Execute always
  - template: template.yml
    parameters:
      scenario: Execute only on main branch
      executeScenario: ${{ eq(variables['Build.SourceBranchName'], 'main') }}
