trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: template.yml
    parameters:
      scenario: all
  - template: template.yml
    parameters:
      scenario: main only
      executeScenario: ${{ eq(variables['Build.SourceBranchName'], 'main') }}
