trigger:
  - '*'
  # - main

pool:
  vmImage: 'ubuntu-latest'

# variables:
  # planet: Hoth
  # fight: true
  # mood: motivated

steps:
  - template: template.yml
    parameters:
      scenario: Execute always
  - template: template.yml
    parameters:
      scenario: Execute only on main branch
      executeScenario: ${{ eq(variables['Build.SourceBranchName'], 'main') }}
  # - template: template.yml
  # - template: template.yml
  #   parameters:
  #     shipName: X-wing
  # - template: template.yml
  #   parameters:
  #     planet: $(planet)
  # - template: template.yml
  # - template: template.yml
  #   parameters:
  #     # fight: ${{ variables.fight }}
  #     fight: $(fight)
  # - template: template.yml
  # - template: template.yml
  #   parameters:
  #     planet: $(planet)
  #     fight: ${{ variables.fight }}
      # fight: $(fight)
  # - template: template.yml
  #   parameters:
  #     fight: eq(variables.mood, 'motivated')
